### ISSUE TITLE
`BoxedUint` support

### ISSUE THREAD

**Issue by tarcieri** [entropyxyz/crypto-primes#34]
`crypto-bigint` v0.6.0-pre.0 has a much more featureful `BoxedUint` type than previous releases which hopefully supports all of the prerequisites required for random prime generation: https://docs.rs/crypto-bigint/0.6.0-pre.0/crypto_bigint/struct.BoxedUint.html

We would like to [migrate from `num-bigint-dig` to `crypto-bigint` in the `rsa` crate](https://github.com/RustCrypto/RSA/issues/390), notably because the [current implementation has a timing sidechannel vulnerability](https://github.com/RustCrypto/RSA/issues/19#issuecomment-1822995643). A full migration will require prime generation / primality testing, hence my interest in this issue.

**Comment by fjarri** [comment]
We will need something like the traits described in https://github.com/RustCrypto/crypto-bigint/issues/70#issuecomment-1699951193 to generalize the methods over `Uint`/`BoxedUint`

**Comment by fjarri** [comment]
I've made a draft PR to see what kind of traits we need for `crypto-primes` to work
