### ISSUE TITLE
CI: codecov runs fail with 429 during upload

### ISSUE THREAD

**Issue by dvdplm** [entropyxyz/crypto-primes#44]
There seems to be an issue with the codecov upload action in this repo. Possibly the GH Action is outdated or the `CODECOV_TOKEN` secret is wrong?

See [this](https://github.com/entropyxyz/crypto-primes/actions/runs/10861321391/job/30149576771?pr=43#step:6:34) for an example failure.

**Comment by fjarri** [comment]
Possibly caused by an outdated codecov action version, I bumped it in #45, and the codecov action passed. Closing for now, reopen if it happens again.
