### ISSUE TITLE
Investigate: can we do faster Jacobi symbol calculation with binary GCD?

### ISSUE THREAD

**Issue by dvdplm** [entropyxyz/crypto-primes#57]
Given calculating the Jacobi symbol is a costly part of the Lucas test, it's worth investigating if we can make it faster by applying binary gcd.

**Comment by lleoha** [comment]
For reference, OpenSSL does GCD (although not binary GCD) to compute Jacobi symbol.
https://github.com/openssl/openssl/blob/master/crypto/bn/bn_kron.c

**Comment by fjarri** [comment]
Looks like the same method we use actually. It's not exactly GCD since there's no modulo calculation required (except modulo 4 and 8, which is trivial).

**Comment by lleoha** [comment]
> Looks like the same method we use actually. It's not exactly GCD since there's no modulo calculation required (except modulo 4 and 8, which is trivial).

Yeah, @fjarri you're right, but isn't this exactly the step of GCD?
```c
        /* (A, B) := (B mod |A|, |A|) */
        err = !BN_nnmod(B, B, A, ctx);
        // ...
        tmp = A;
        A = B;
        B = tmp;
        // ...
```
https://github.com/openssl/openssl/blob/master/crypto/bn/bn_kron.c#L125

**Comment by fjarri** [comment]
Actually, I was mistaken too, we also have modulo calculation here. But either way, I think the algorithm in OpenSSL is the same as the one we use.

**Comment by dvdplm** [comment]
FWIW I have benchmarked the approach in this crate against a few others and found this one to have very good performance compared to status quo (e.g. the algo proposed here: https://eprint.iacr.org/2024/1054).

**Comment by dvdplm** [comment]
I would actually be inclined to close this issue @fjarri.

**Comment by fjarri** [comment]
I agree. I think our current implementation is good enough.
