### ISSUE TITLE
Switch from library panic to return an Error or other invalid return

### ISSUE THREAD

**Issue by ok-john** [entropyxyz/crypto-primes#8]
Currently `jacobi_symbol` panics when `p` is even - perhaps this should return and Error, maybe -1? 

```Rust 
/// Returns the Jacobi symbol `(a/p)` given an odd `p`. Panics on even `p`.
pub(crate) fn jacobi_symbol<const L: usize>(a: i32, p_long: &Uint<L>) -> JacobiSymbol {
```

Idea being that any dependent libraries who import this function can handle errors/panics instead of the underlying library panicing.

**Comment by fjarri** [comment]
`jacobi_symbol()` takes an `Odd`-wrapped integer since #38, so this is no longer an issue.
